version: "3.9"

services:
  db:
    ports:
      - "5440:5432"
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dsadsa 
      POSTGRES_USER : super

  dev:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - db
    environment:
      - APP_NAME=todo
      - DB_NAME=todo
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=super
      - DB_PASSWORD=dsadsa
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    network_mode: service:db

  api:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    depends_on:
      - db
    ports:
      - "3001:80"
    environment:
      - APP_NAME=todo
      - DB_NAME=todo
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=super
      - DB_PASSWORD=dsadsa
    volumes:
      - ./:/app/
    command: /start-reload.sh

  pytest:
    build: 
      dockerfile: Dockerfile
      context: .
      target: dev
    depends_on:
      - db
    environment:
      - APP_NAME=todo
      - DB_NAME=todo_test
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=super
      - DB_PASSWORD=dsadsa
      - ENVIRONMENT=testing
    volumes:
      - ./:/app/
    command: pytest


volumes:
  postgres:
